#!/bin/sh

NAME=vlmcsd
DAEMON=/usr/sbin/$NAME
LOGFILE=/var/log/$NAME.log

[ -x $DAEMON ] || exit 0

case "$1" in
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -x $DAEMON -- -l $LOGFILE
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon -K -q -n $NAME
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
